// Product data
const products = [
    {
        id: 1,
        name: "Wireless Bluetooth Headphones",
        category: "Electronics",
        price: 79.99,
        oldPrice: 129.99,
        image: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        badge: "Sale",
        rating: 4.5,
        ratingCount: 128,
        description: "Experience premium sound quality with these comfortable wireless headphones.",
        stock: 15,
        isFeatured: true
    },
    {
        id: 2,
        name: "Smart Fitness Tracker",
        category: "Electronics",
        price: 49.99,
        oldPrice: 69.99,
        image: "https://images.pexels.com/photos/4482900/pexels-photo-4482900.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        badge: "Bestseller",
        rating: 4.8,
        ratingCount: 256,
        description: "Track your fitness goals with this waterproof smart tracker.",
        stock: 22,
        isFeatured: true
    },
    {
        id: 3,
        name: "Premium Leather Wallet",
        category: "Fashion",
        price: 39.99,
        oldPrice: null,
        image: "https://images.pexels.com/photos/2079438/pexels-photo-2079438.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        badge: null,
        rating: 4.6,
        ratingCount: 89,
        description: "Handcrafted genuine leather wallet with RFID protection.",
        stock: 18,
        isFeatured: true
    },
    {
        id: 4,
        name: "Stainless Steel Water Bottle",
        category: "Home & Kitchen",
        price: 24.99,
        oldPrice: 34.99,
        image: "https://images.pexels.com/photos/4000090/pexels-photo-4000090.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        badge: "Eco-friendly",
        rating: 4.7,
        ratingCount: 112,
        description: "Double-walled insulated water bottle that keeps drinks cold for 24 hours.",
        stock: 30,
        isFeatured: true
    },
    {
        id: 5,
        name: "Organic Face Serum",
        category: "Beauty",
        price: 29.99,
        oldPrice: null,
        image: "https://images.pexels.com/photos/4465124/pexels-photo-4465124.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        badge: "New",
        rating: 4.4,
        ratingCount: 76,
        description: "Hydrating face serum made with organic ingredients.",
        stock: 25,
        isFeatured: true
    },
    {
        id: 6,
        name: "Wireless Charging Pad",
        category: "Electronics",
        price: 19.99,
        oldPrice: 29.99,
        image: "https://images.pexels.com/photos/4526407/pexels-photo-4526407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        badge: "Sale",
        rating: 4.3,
        ratingCount: 94,
        description: "Fast wireless charging pad compatible with all Qi-enabled devices.",
        stock: 20,
        isFeatured: true
    },
    {
        id: 7,
        name: "Ceramic Coffee Mug Set",
        category: "Home & Kitchen",
        price: 34.99,
        oldPrice: null,
        image: "https://images.pexels.com/photos/6306720/pexels-photo-6306720.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        badge: null,
        rating: 4.9,
        ratingCount: 68,
        description: "Set of 4 handcrafted ceramic coffee mugs.",
        stock: 12,
        isFeatured: true
    },
    {
        id: 8,
        name: "Cotton T-Shirt",
        category: "Fashion",
        price: 19.99,
        oldPrice: null,
        image: "https://images.pexels.com/photos/5698851/pexels-photo-5698851.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        badge: null,
        rating: 4.5,
        ratingCount: 132,
        description: "Premium cotton t-shirt with a comfortable fit.",
        stock: 45,
        isFeatured: true
    }
]; 